### ISSUE TITLE
index

### ISSUE THREAD

**Issue by Sibiya666** [dedmagic/react-effector#10]
https://github.com/dedmagic/react-effector/blob/5dcfb83517740c526977f4826313406953a17412/src/components/common/index.ts#L2

**Comment by Sibiya666** [comment]
а можно так же завести index)

**Comment by dedmagic** [comment]
Вот здесь не понял -- для чего завести `index`? Для `card`? Но там и так один модуль.
Просто для того, чтобы в одном месте вместо `./card/card` написать `./card`? Ну не знаю...

**Comment by Sibiya666** [comment]
теперь знаешь)

**Comment by dedmagic** [comment]
`index` есть на уровне выше (в `common`), поэтому импортироваться в клиентском коде это будет так:
```js
import { Card, Column, Table } from "components/common";
```

Поэтому создание `index` для `card`, КМК, никаких выгод не несёт. Создавать ещё один файл только для того, чтобы в _единственном_ месте вместо `./card/card` написать `./card` -- не стоит оно того. 😄
