### ISSUE TITLE
focus-trap-react

### ISSUE THREAD

**Issue by Sibiya666** [dedmagic/react-effector#12]
https://github.com/dedmagic/react-effector/blob/5dcfb83517740c526977f4826313406953a17412/src/components/common/modal/modal.tsx#L37

**Comment by Sibiya666** [comment]
на досуге рассмотри focus-trap-react библиотеку, позволяет фиксировать фокус, не дает уводить пользователя с модалок

**Comment by dedmagic** [comment]
Не, так как главная цель УП -- всё попробовать/потрогать самому, то использование библиотек по минимуму.

К тому же сейчас модалка работает (почти) как надо, планирую ещё сделать закрытие по Enter, и всё.
