### ISSUE TITLE
generic

### ISSUE THREAD

**Issue by Sibiya666** [dedmagic/react-effector#13]
https://github.com/dedmagic/react-effector/blob/5dcfb83517740c526977f4826313406953a17412/src/components/common/table/table.tsx#L5

**Comment by Sibiya666** [comment]
тут бы generic добавить или пот таблицу структуру придумать

**Comment by dedmagic** [comment]
Упс... Забыл создать ветку, работал в мастере.
[commit](https://github.com/dedmagic/react-effector/commit/a420dcdb185a8bbe929e90211751fafcafef3985)
