### ISSUE TITLE
useMemo

### ISSUE THREAD

**Issue by Sibiya666** [dedmagic/react-effector#17]
https://github.com/dedmagic/react-effector/blob/26631085b5778a2c88d37f9030f2d5ed9a715c4b/src/components/common/table/table.tsx#L11

**Comment by Sibiya666** [comment]
рассмотри вариант того что бы запихнуть функции в useCallback, а для вычисляемых значения useMemo

**Comment by dedmagic** [comment]
`useMemo`, как я понимаю, неприменим к функциям с параметрами. А здесь все три именно такие.

**Comment by dedmagic** [comment]
`useCallback` нужен в случае передачи функции в дочерний компонент. Так что тоже здесь его негде использовать.
