### ISSUE TITLE
Компонент внутри компонента

### ISSUE THREAD

**Issue by Sibiya666** [dedmagic/react-effector#19]
https://github.com/dedmagic/react-effector/blob/26631085b5778a2c88d37f9030f2d5ed9a715c4b/src/components/pages/positions/edit-dialog.tsx#L28

**Comment by Sibiya666** [comment]
такие вещи выносим в отдельный компонент, декомпозируем

**Comment by dedmagic** [comment]
Имеем компонент "диалог", внутрь которого вставляется компонент "форма". Вопрос: где хранить состояние формы?

Логично, что оно должно быть в компоненте формы, но тогда перестаёт работать `SaveForm`, которая вызывается на уровне диалога, но использует стейт формы -- этот стейт ей недоступен.

Если хранить весь стейт в диалоге, то надо будет в компонент формы передавать туеву хучу пропсов -- по два на каждое поле формы + ещё дополнительные.

Как быть-то?

**Comment by dedmagic** [comment]
В общем, я вижу два варианта:
1. Lifting State Up.
2. Использование стейт-менеджера.

Возможно, есть другие, но я их не знаю.

С первым вариантом всё очевидно и понятно, поэтому буду думать/пробовать за второй 😄.

**Comment by Sibiya666** [comment]
самый простой и примитивный вариант для этой модалки это children. в children разместить форму. прям в рамках одного компонента, форму даже не придется выносить.

**Comment by dedmagic** [comment]
Но ведь тогда нет выноса формы в отдельный компонент и декомпозиции.

И мне не ясна разница: форма как атрибут (текущий вариант) или форма как children -- в чём принципиальные различия?

**Comment by Sibiya666** [comment]
childred собственно это вложенность для основного контента, но есть нюанс мы это вложенностью не можем управлять, то есть вставили в одно конкретное место да и все. 
здесь форма как раз и будет этим основным контентом.

если бы мы хотели менять конкретные плейсхолдеры нашего компонента, то передавали бы через пропсы. 

декомпозиация: 
1.  у тебя есть ui компонент модалки, который служим шаблоном для реализации  конкретных модалок. 
2.  заводишь компонент в разметке которого, есть модалка, в чилдрен модалки идет форма.  у тебя получается компонент конкретной модалки. 
3. получившийся компонент может а) принимать колбека на отправку формы/отмену б)  принимать стартовые значения формы

**Comment by dedmagic** [comment]
Я правильно понял, что вместо левой схемы мы получаем правую?
![изображение](https://user-images.githubusercontent.com/17004073/219002431-f4f2a85a-9ff0-43b3-96f2-ec0ba8facfc3.png)

Если да, то с точки зрения хранения стейта они идентичны -- весь стейт в самом верхнем общем компоненте. Lifting State Up в полный рост.

**Comment by dedmagic** [comment]
Сделал через `children`. Easy 😃

**Comment by dedmagic** [comment]
Сделал вынос компонента формы с хранением стейта в родительском компоненте (`EditDialog`), т.е. lifting state up.

https://github.com/dedmagic/react-effector/pull/39. Этот ПР вливать не буду, пусть код в отдельной ветке лежит.

**Comment by dedmagic** [comment]
Сделал вариант со стором для формы: https://github.com/dedmagic/react-effector/pull/40

**Comment by dedmagic** [comment]
Сделал ещё один вариант: в родительском компоненте создаются ref-ы, которые передаются в дочерний (форму): https://github.com/dedmagic/react-effector/pull/41/files

**Comment by dedmagic** [comment]
Осталось выбрать, какой из трёх вариантов заиспользовать. Выношу на голосование :).

См. прикреплённые к ишью пулл-реквесты.

**Comment by aristov-y** [comment]
Почему слил все три?
Достаточно было #36

**Comment by dedmagic** [comment]
37-ой убрал мелкие косяки, оставшиеся после 35-го, но с ним залетел в репозиторий мусор (по невнимательности), который убрал 38-м.

**Comment by dedmagic** [comment]
@Sibiya666 Влил вариант со стором, ишью закрываю.
