### ISSUE TITLE
UseEffect

### ISSUE THREAD

**Issue by Sibiya666** [dedmagic/react-effector#20]
https://github.com/dedmagic/react-effector/blob/26631085b5778a2c88d37f9030f2d5ed9a715c4b/src/components/pages/positions/edit-dialog.tsx#L24

**Comment by Sibiya666** [comment]
Попробуй без useEffect, а при инициализации useState установить данные значения

**Comment by dedmagic** [comment]
Нет, так не работает. `useState` инициализируется один раз при создании компонента, и при попытке открывать окно редактирования для разных записей в нём будет всегда одно и то же, то что попало в стейт изначально.

Именно поэтому и нужен `useEffect`, завязанный на изменение `position`.

**Comment by dedmagic** [comment]
Теперь вопрос вообще отпал, т.к. вместо `useState` использовано `useRef`.
