### ISSUE TITLE
useRef

### ISSUE THREAD

**Issue by Sibiya666** [dedmagic/react-effector#21]
https://github.com/dedmagic/react-effector/blob/26631085b5778a2c88d37f9030f2d5ed9a715c4b/src/components/pages/positions/edit-dialog.tsx#L20

**Comment by Sibiya666** [comment]
у тебя есть уже стартовые значения в пропах, если их надо поставить в input, то передавай в input value. что бы их достать при отправке формы, добавь intput в useRef и из него тащи value

**Comment by dedmagic** [comment]
Особых преимуществ не увидел. Вместо создания стейта на каждое поле формы создаём реф на каждое поле формы. Пропадает `useEffect` для корректной инициализации полей, но появляются мегаприседания для того, чтобы достать значения полей (см. пулл-реквест).
