### ISSUE TITLE
Стилистика if/else

### ISSUE THREAD

**Issue by Sibiya666** [dedmagic/react-effector#24]
https://github.com/dedmagic/react-effector/blob/26631085b5778a2c88d37f9030f2d5ed9a715c4b/src/components/pages/positions/positions.tsx#L74

**Comment by Sibiya666** [comment]
если мы точно знаем, что второй вариант работает при  отрицательном прохождении условия, то можно не писать else, а в if поставить return

**Comment by dedmagic** [comment]
А как насчёт такого варианта?

```js
position.id ? updatePosition(position) : createPosition(position);
```

**Comment by Sibiya666** [comment]
да и первоначальный вариант нормальный, как еще вариант накидываю)

**Comment by dedmagic** [comment]
Не, `else` зло и от него надо избавляться.

С твоей точки зрения, что лучше:
```js
position.id ? updatePosition(position) : createPosition(position);
```
или
```js
if (position.id) {
  updatePosition(position);
  return;
}
createPosition(position);
```

**Comment by Sibiya666** [comment]
для методов тернарник лично мне не нравится. есть практики?

**Comment by dedmagic** [comment]
А какая разница (в этом контексте) -- метод или обычная функция?

**Comment by Sibiya666** [comment]
```
const some = true;
  function func() {
    alert(1);
  }

  some && func();
  ```
  для меня как и тут срабатывает мнение, что мы ожидаем там возвращение значения.

**Comment by dedmagic** [comment]
А, т.е. тут не про метод, тут про `void`, как я понимаю.
Да, это хак, несомненно. Хаки это не только хорошо, но и плохо.
ОК, сделаю с `if`-ом.
