### ISSUE TITLE
Структура

### ISSUE THREAD

**Issue by Sibiya666** [dedmagic/react-effector#4]
Assets как правильно это статика приложения, то что у тебя в public находится
Components это общий блок. Он может присутствовать как уровне модула, так  и на уровне приложения, тогда это shared components, которые используются в нескольких модулях и страницах. 

к примеру, как можно переработать то что сейчас есть
![image](https://user-images.githubusercontent.com/13837887/216805330-66e2c89a-36ba-425a-be52-2c2d690152a5.png)
Assets вынес на корневой уровень, переместил содержимое public туда. 

![image](https://user-images.githubusercontent.com/13837887/216805386-9ce2fde3-ce37-4d2a-a3e3-858974c476cb.png)
рабочая область кода src включает в себя:
1. app, как стартовая область приложения. 
2. components здесь в качестве shared components
3. models так же  shared,  элменты модели, которые могут быть использованы по всему приложению 
4. pages это уже модули/сервис/роут те сигменты приложения, которые несут в себе обособленный и законченный бизнес блок нашего приложения, который в свою очередь состоит из элементов этого бизнес блок. я бы выбирал здесь привязку к роуту. и тогда было что modules=>nameOfModule=>pagesOfModules 
![image](https://user-images.githubusercontent.com/13837887/216805670-6b4efc55-e2af-43d4-b262-dcfeeb792150.png)
папку компонента можно разбить на две части, если появляется свой доп ui или utils, const. в ui хранил бы отдельный ui элементы компоненты, а в lib утилиты, константы и тп
![image](https://user-images.githubusercontent.com/13837887/216805740-29947237-3dd2-4121-8a24-df8c52571954.png)
5. на уровне проекта можно было бы так же завести common , в котором держать служебные api сервисы или вспомогательные сервисы, которые не являются часть ui. к примеру, авторизацию, работу с localStorage

**Comment by dedmagic** [comment]
В более крупном приложении, где "модуль" -- это набор страниц, абсолютно согласен, уровень иерархии "модуль" необходим. Здесь же "один модуль" == "одна страница", поэтому введение модулей излишне, ИМХО. По крайней мере -- пока.

**Comment by dedmagic** [comment]
Про деление внутри страницы на `ui` и `lib` тоже, пока необходимости не вижу. Если таковая появится, то тогда, конечно, буду вводить эти подпапки.

**Comment by dedmagic** [comment]
В `README.md` описал структуру проекта, как я её вижу.

**Comment by Sibiya666** [comment]
у тебя переквалификация. тебе надо все попробовать)

**Comment by dedmagic** [comment]
Уговорил :)

1. Вынес `app` в корень.
2. В `components` теперь только общие (shared) компоненты.
3. Появились модули `busines-logic` и `support`, в каждом папки `pages` и `shared`.
4. Папки `shared` и каждой страницы содержат подпапки `ui` и `lib`.

Обновил описание структуры в `README.md`.
