### ISSUE TITLE
Ненужная зависимоть хука

### ISSUE THREAD

**Issue by aristov-y** [dedmagic/react-effector#42]
https://github.com/dedmagic/react-effector/blob/4f012ca07fd0f6ef242a6de0a239565350693d41/src/hooks/use-toggle.ts#L7-L13

в useCallback используется зависимость на toggle, которую можно убрать если использовать синтаксис:
```js
setToggle(oldValue => !oldValue)
```
можно просто внести значение для newValue полностью в сеттер состояния

**Comment by dedmagic** [comment]
@aristov-y  Зависимость от `toggle` убрал.

Фразу "можно просто внести значение для newValue полностью в сеттер состояния" не понял -- можешь пояснить?

**Comment by aristov-y** [comment]
Вот так
```js
const toggler = useCallback((value?: boolean) => {
  setToggle(oldValue => (typeof value === "boolean" ? value : !oldValue)); 
}, []);
```
