### ISSUE TITLE
Обработка ошибок при работе с effector

### ISSUE THREAD

**Issue by Sibiya666** [dedmagic/react-effector#55]
https://github.com/dedmagic/react-effector/blob/0f04e421561df328912da5173eba9c601c7320a9/src/api/position-api.ts#L12

у Fx есть есть failData, который как раз и занимается обработкой ошибок. 
https://effector.dev/docs/api/effector/effect#faildata

**Comment by dedmagic** [comment]
Как я понимаю, подавить вывод ошибки в консоль при провалившемся `fetch` – невозможно?
![изображение](https://user-images.githubusercontent.com/17004073/224208339-0b51eab8-3ff2-44d8-9aa9-e0506bc2d5fd.png)
