### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by Sibiya666** [dedmagic/react-effector#56]
Сейчас у тебя в "моделях" есть store.ts. По факту это модель описывающая работу с positions. Предлагаю тогда и обозвать не store, а position.ts. так каждая модель будет в своем отдельном, и мы не будем их смешивать.

**Comment by dedmagic** [comment]
Таки `models/position/store.ts` -- каждая модель будет в своей подпапке, и мы не будем их смешивать.

**Comment by Sibiya666** [comment]
отвечаешь в закрытые issues?)

**Comment by dedmagic** [comment]
Почему нет? :)
