### ISSUE TITLE
Нельзя задавать внешние отступы БЭМ-блокам

### ISSUE THREAD

**Issue by ShukshinaMI** [dedmagic/react-effector#58]
1. Если card-title - это все же блок, тогда ему нельзя задавать внешние отступы.
2. Почему вынесли card-title в отдельный блок? почему нельзя сделать его элементом? тогда можно будет задавать внешние отступы

```
.card {
...
.card-title {
  /* size & indents */
  margin: 24px;
}
```

**Comment by dedmagic** [comment]
1. На данном проекте БЭМ не используется, соответственно, понятий "блок" и "элемент" нет.
Может быть речь о том, чтобы сделать стили зависимыми, т.е. вместо `.card-title` нужно `.card .title`?
2. Уточняющий вопрос: у `.card` тоже есть внешний отступ (`.margin-left`) -- это тоже ошибка?

**Comment by dedmagic** [comment]
https://github.com/dedmagic/react-effector/commit/a66f9e4931d0502077780d1af4bc859eda3d996c

**Comment by ShukshinaMI** [comment]
Возможно не верно поняла постановку задачи, думала оцениваются и основы разработки, в программе "Основы разработки frontend" для разработчика есть тема "Умение наименования CSS классов по БЭМ"

**Comment by dedmagic** [comment]
В этом проекте отражена только часть тем из программы (ибо нельзя объять необъятное 😀), акцент на React/Effector. CSS нативный, без препроцессоров и методологий.

Для вёрстки, видимо, нужно отдельный проект (проекты?) замутить. Маша, есть какие-нибудь рекомендации или готовые задания по подобным проектам? Или можно просто взять любой макет и вперёд, в ~~светлое будущее~~ БЭМ/SASS/LESS/...?
