### ISSUE TITLE
css selector

### ISSUE THREAD

**Issue by Sibiya666** [dedmagic/react-effector#8]
https://github.com/dedmagic/react-effector/blob/5dcfb83517740c526977f4826313406953a17412/src/components/app/main/content/content.css#L1

**Comment by Sibiya666** [comment]
Экспериментировал? или уже возникли проблемы со специфичность?)

**Comment by dedmagic** [comment]
Почему проблемы? Есть такой элемент: `<main className="content">`, я для него задавал стили и всё.
