### ISSUE TITLE
Порядок css свойств

### ISSUE THREAD

**Issue by Sibiya666** [dedmagic/react-effector#9]
https://github.com/dedmagic/react-effector/blob/5dcfb83517740c526977f4826313406953a17412/src/components/app/header/header.css#L10

**Comment by Sibiya666** [comment]
Ознакомься с такой статьей https://learn.javascript.ru/css-format

я придерживаюсь следующего:
1. позиционирование
position
left/right/top/bottom
2. блочная модель
block
flex/grid - dependensies
3. отступы
padding/margin
4. границы
border
5. шрифты
font
color
6. подложка
background
7. z - index

**Comment by dedmagic** [comment]
Да, я уже упорядочил правила, только это в отдельной ветке лежало (`css-order`). И статью эту читал :)

Только у меня несколько другая система:
- position: положение на странице
- size & indents: размеры и отступы
- borders: границы
- appearance: внешний вид
- content: управление расположением контента/дочерних элементов
